apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
  namespace: jenkins-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product
          image: 052937454741.dkr.ecr.ap-northeast-2.amazonaws.com/12st-user11-product:${BUILD_NUMBER}
          ports:
            - containerPort: 8080
